---
title: "Leslie Matrix Practice"
format: html
editor: visual
---

```{r}

# Make a sequence of values from -1 to 10

my_values <- seq(from = 1, to = 10, by = 1)
my_values

# Convert to a matrix

my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)

# Look at matrix
my_matrix

```

```{r}
# Don't have enough elements or have too many in matrix 

matrix(data = my_values, 
       nrow = 3,
       ncol = 4, byrow = TRUE)

# Always look at data
```

```{r}
# Matrix Math 

4 * my_matrix

```

```{r}
my_values2 <- seq(from = 21, to = 30)
my_matrix2 <- matrix(my_values2, nrow = 2, byrow = TRUE)
my_matrix2
```

```{r}
my_matrix + my_matrix2
my_matrix - my_matrix2

```

# Matrix Multiplication

```{r}

cats <- matrix(data = c(0, 4, 3, 1), nrow = 2, byrow = TRUE)

cats

dogs <- matrix(data = c(6, -3, 0, 2), nrow = 2, byrow = TRUE)
dogs
```

```{r}
cats %*% dogs
```

# Leslie Matrix Example

## Create the projection matrix: 

```{r}
# create matrix

insect_leslie <- matrix(c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), nrow = 3, ncol = 3, byrow = TRUE)
# Look at matrix
insect_leslie

```

## Specify an initial condition 

```{r}
# Insect lifestage population year 0 

insect_y0 <- c(12000, 700, 500)
```

## Find population for each life stage at year 1

```{r}
# Population at year 1 

insect_y1 <- insect_leslie %*% insect_y0

insect_y1
```

```{r}
# Population by lifestage at year 2
insect_y2 <- insect_leslie %*% insect_y1
insect_y2
```

```{r}
# Population by lifestage at year 3 
insect_y3 <- insect_leslie %*% insect_y2
insect_y3
```

```{r}
# Population by lifestage at year 4 
insect_y4 <- insect_leslie %*% insect_y3
insect_y4
```

## Another Leslie Matrix example 

```{r}
# Make the projection matrix 

tree_leslie <- matrix(c(0, 0, 5000, 0.1, 0, 0, 0, 0.06, 0.95), nrow = 3, ncol = 3, byrow = TRUE )
tree_leslie
```

### Make some projections 

```{r}
# year 0, initial condition 

tree_0 <- c(5000, 0, 0)

tree_1 <- tree_leslie %*% tree_0
tree_1
```

```{r}
# year 2
tree_2 <- tree_leslie %*% tree_1 
tree_2
```

```{r}
# year 3 
tree_3 <- tree_leslie %*% tree_2
tree_3
```

```{r}
# year 4 
tree_4 <- tree_leslie %*% tree_3
tree_4
```

## Sending modified file to GH
